/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckBox: typeof import('./src/components/CheckBox.vue')['default']
    Condition: typeof import('./src/components/Condition.vue')['default']
    ConditionItem: typeof import('./src/components/ConditionItem.vue')['default']
    DuePicker: typeof import('./src/components/DuePicker.vue')['default']
    EventAction: typeof import('./src/components/EventAction.vue')['default']
    EventActionTargetItem: typeof import('./src/components/EventActionTargetItem.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    NumberInput: typeof import('./src/components/NumberInput.vue')['default']
    NumberInput2: typeof import('./src/components/NumberInput2.vue')['default']
    OuterBlock: typeof import('./src/components/OuterBlock.vue')['default']
    RepeatFrequency: typeof import('./src/components/RepeatFrequency.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    SpecifyDate: typeof import('./src/components/SpecifyDate.vue')['default']
    TCEventEditorApp: typeof import('./src/components/TCEventEditorApp.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    ToggleCheckBox: typeof import('./src/components/ToggleCheckBox.vue')['default']
  }
}
